# Locate FBX
# This module defines:
# FBX_INCLUDE_DIR, where to find the headers
#
# FBX_LIBRARY, FBX_LIBRARY_DEBUG
# FBX_FOUND
#
# $FBX_DIR is an environment variable that would
# correspond to the ./configure --prefix=$FBX_DIR


IF(APPLE)
  if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    # using regular Clang or AppleClang
    SET(FBX_LIBDIR "clang")
  else()
    SET(FBX_LIBDIR "gcc4/ub")
  endif()
ELSEIF(CMAKE_COMPILER_IS_GNUCXX)
    SET(FBX_LIBDIR "gcc4")
ELSEIF(MSVC80)
    SET(FBX_LIBDIR "vs2005")
ELSEIF(MSVC90)
    SET(FBX_LIBDIR "vs2008")
ELSEIF(MSVC10)
    SET(FBX_LIBDIR "vs2010")
ELSEIF(MSVC11)
    SET(FBX_LIBDIR "vs2012")
ELSEIF(MSVC_VERSION EQUAL 1800)
    SET(FBX_LIBDIR "vs2013")
ELSEIF(MSVC_VERSION EQUAL 1900)
    SET(FBX_LIBDIR "vs2015")
ELSEIF(MSVC_VERSION GREATER_EQUAL 1910 AND MSVC_VERSION LESS 1920)
    SET(FBX_LIBDIR "vs2017")
ELSEIF(MSVC_VERSION GREATER_EQUAL 1920 AND MSVC_VERSION LESS 1930)
   SET(FBX_LIBDIR "vs2019") # FBX doesn't have this yet as of version 2020.0.1
   SET(FBX_COMPAT_LIBDIR "vs2019" "vs2017") # Binary compatible with vs2022
ELSEIF(MSVC_VERSION GREATER_EQUAL 1930 AND MSVC_VERSION LESS 1950)
#Visual Studio 2022 version 17.2 = 1932
   SET(FBX_LIBDIR "vs2022")
   # FBX doesn't have this yet as of version 2020.0.1
   # FBX 2019 IS IN version 2020.3.1
   SET(FBX_COMPAT_LIBDIR "vs2022" "vs2019" "vs2017") # Binary compatible with vs2022
ENDIF()

IF(APPLE)
    # do nothing
ELSEIF(CMAKE_CL_64)
    SET(FBX_LIBDIR_PLATFORM /x64)
ELSEIF(CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET(FBX_LIBDIR_PLATFORM /x64)
ELSE()
    SET(FBX_LIBDIR_PLATFORM /x86)
ENDIF()

IF (FBX_LIBDIR_PLATFORM)
    SET(FBX_LIBDIR ${FBX_LIBDIR}${FBX_LIBDIR_PLATFORM})
ENDIF (FBX_LIBDIR_PLATFORM)

#try to use 2015.1 or 2014.2 version

IF(APPLE)
    SET(FBX_LIBNAME "fbxsdk")
ELSEIF(CMAKE_COMPILER_IS_GNUCXX)
    SET(FBX_LIBNAME "fbxsdk")
ELSE()
    OPTION(FBX_SHARED OFF)
    IF(FBX_SHARED)
        SET(FBX_LIBNAME "libfbxsdk")
    ELSE()
        SET(FBX_LIBNAME "libfbxsdk-md")
        IF(WIN32)
            SET(FBX_XML2_LIBNAME "libxml2-md")
            SET(FBX_ZLIB_LIBNAME "zlib-md")
        ENDIF()
    ENDIF()
ENDIF()

SET(FBX_LIBNAME_DEBUG ${FBX_LIBNAME}d)


IF(DEFINED ENV{FBX_DIR})
  IF(IS_DIRECTORY $ENV{FBX_DIR})
    SET( FBX_SEARCH_PATHS ${FBX_SEARCH_PATHS} $ENV{FBX_DIR})
  ENDIF(IS_DIRECTORY $ENV{FBX_DIR})
ENDIF(DEFINED ENV{FBX_DIR})

#IF(IS_DIRECTORY "$OSG_INCLUDE_DIR/../FBX/2020.3.7")
FILE(REAL_PATH "${OSG_INCLUDE_DIR}/../FBX" VCPKGED_FBX_DIR)
MESSAGE("FIND FBX LIST_FBX_VERSIONS ${VCPKGED_FBX_DIR}")
IF(IS_DIRECTORY "${VCPKGED_FBX_DIR}")
  MESSAGE("ADD FBX LIST_FBX_VERSIONS ${VCPKGED_FBX_DIR}")
  file(GLOB LIST_FBX_VERSIONS LIST_DIRECTORIES true RELATIVE "${VCPKGED_FBX_DIR}" "${VCPKGED_FBX_DIR}/*/")
  FOREACH( FBX_VERSION ${LIST_FBX_VERSIONS})
    MESSAGE("ADD FBX VERSION ${FBX_VERSION}")
    SET( FBX_SEARCH_PATHS ${FBX_SEARCH_PATHS} "${VCPKGED_FBX_DIR}/${FBX_VERSION}")
  ENDFOREACH()
ENDIF()

SET( FBX_VERSIONS 2020.3.4 2020.3.1 2020.0.1 2020.0 2019.5 2019.2 2019.0 2018.1.1 2018.0 2017.1 2016.1.2 2015.1 2014.2)
FOREACH( FBX_VERSION ${FBX_VERSIONS} )
  IF(IS_DIRECTORY "$ENV{ProgramW6432}/Autodesk/FBX/FBX SDK/${FBX_VERSION}")
    SET( FBX_SEARCH_PATHS ${FBX_SEARCH_PATHS} "$ENV{ProgramW6432}/Autodesk/FBX/FBX SDK/${FBX_VERSION}")
  ENDIF(IS_DIRECTORY "$ENV{ProgramW6432}/Autodesk/FBX/FBX SDK/${FBX_VERSION}")
  IF(IS_DIRECTORY "$ENV{PROGRAMFILES}/Autodesk/FBX/FBX SDK/${FBX_VERSION}")
    SET( FBX_SEARCH_PATHS ${FBX_SEARCH_PATHS} "$ENV{PROGRAMFILES}/Autodesk/FBX/FBX SDK/${FBX_VERSION}")
  ENDIF(IS_DIRECTORY "$ENV{PROGRAMFILES}/Autodesk/FBX/FBX SDK/${FBX_VERSION}")
  IF(IS_DIRECTORY "/Applications/Autodesk/FBX SDK/${FBX_VERSION}")
    SET( FBX_SEARCH_PATHS ${FBX_SEARCH_PATHS} "/Applications/Autodesk/FBX SDK/${FBX_VERSION}")
  ENDIF(IS_DIRECTORY "/Applications/Autodesk/FBX SDK/${FBX_VERSION}")
ENDFOREACH( FBX_VERSION ${FBX_VERSIONS} )

#VERY OLD VERSIONS
SET( FBX_OLD_VERSIONS 201612 201611 20151 20142)
FOREACH( FBX_VERSION ${FBX_OLD_VERSIONS} )
  IF(IS_DIRECTORY "/Applications/Autodesk/FBXSDK${FBX_VERSION}")
    SET( FBX_SEARCH_PATHS ${FBX_SEARCH_PATHS} "/Applications/Autodesk/FBXSDK${FBX_VERSION}")
  ENDIF(IS_DIRECTORY "/Applications/Autodesk/FBXSDK${FBX_VERSION}")
ENDFOREACH( FBX_VERSION ${FBX_OLD_VERSIONS} )

# search for headers & debug/release libraries
MESSAGE("SEARCH include/fbxsdk.h in ${FBX_SEARCH_PATHS}")
FIND_PATH(FBX_INCLUDE_DIR "fbxsdk.h"
    PATHS ${FBX_SEARCH_PATHS}
    PATH_SUFFIXES "include")

# search for compatible library
FOREACH( MYPATH ${FBX_COMPAT_LIBDIR} )
    SET(RELEASE_PATH_SUFFIXES ${RELEASE_PATH_SUFFIXES} "lib/${MYPATH}${FBX_LIBDIR_PLATFORM}/release" "lib/${MYPATH}${FBX_LIBDIR_PLATFORM}")
    SET(DEBUG_PATH_SUFFIXES ${DEBUG_PATH_SUFFIXES} "lib/${MYPATH}${FBX_LIBDIR_PLATFORM}/debug")
    SET(GENERAL_PATH_SUFFIXES ${GENERAL_PATH_SUFFIXES} "lib/${MYPATH}${FBX_LIBDIR_PLATFORM}")
	MESSAGE("PATH_SUFFIX ${MYPATH} ADDED.")
ENDFOREACH( MYPATH ${FBX_COMPAT_LIBDIR} )

    SET(RELEASE_PATH_SUFFIXES ${RELEASE_PATH_SUFFIXES} "lib/${FBX_LIBDIR_PLATFORM}/release")
    SET(DEBUG_PATH_SUFFIXES ${DEBUG_PATH_SUFFIXES} "lib/${FBX_LIBDIR_PLATFORM}/debug")
    SET(GENERAL_PATH_SUFFIXES ${GENERAL_PATH_SUFFIXES} "lib/${FBX_LIBDIR_PLATFORM}")

FIND_LIBRARY( FBX_LIBRARY ${FBX_LIBNAME}
    PATHS ${FBX_SEARCH_PATHS}
    PATH_SUFFIXES ${RELEASE_PATH_SUFFIXES})

#Once one of the calls succeeds the result variable will be set and stored in the cache so that no call will search again.

#no debug d suffix, search in debug folder only
FIND_LIBRARY( FBX_LIBRARY_DEBUG ${FBX_LIBNAME}
    PATHS ${FBX_SEARCH_PATHS}
    PATH_SUFFIXES ${DEBUG_PATH_SUFFIXES})
FIND_LIBRARY( FBX_LIBRARY_DEBUG ${FBX_LIBNAME_DEBUG}
    PATHS ${FBX_SEARCH_PATHS}
    PATH_SUFFIXES ${GENERAL_PATH_SUFFIXES})

IF(WIN32)
    FIND_LIBRARY( FBX_XML2_LIBRARY ${FBX_XML2_LIBNAME}
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES ${RELEASE_PATH_SUFFIXES})
    FIND_LIBRARY( FBX_ZLIB_LIBRARY ${FBX_ZLIB_LIBNAME}
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES ${RELEASE_PATH_SUFFIXES})
    FIND_LIBRARY( FBX_XML2_LIBRARY_DEBUG ${FBX_XML2_LIBNAME}
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES ${DEBUG_PATH_SUFFIXES})
    FIND_LIBRARY( FBX_ZLIB_LIBRARY_DEBUG ${FBX_ZLIB_LIBNAME}
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES ${DEBUG_PATH_SUFFIXES})
ENDIF()

IF(FBX_LIBRARY AND FBX_LIBRARY_DEBUG AND FBX_INCLUDE_DIR)
    SET(FBX_FOUND "YES")
ELSE()
    SET(FBX_FOUND "NO")
ENDIF()

IF(NOT FBX_FOUND)
#try to use 2014.1 version
    IF(APPLE)
        SET(FBX_LIBNAME "fbxsdk-2014.1")
    ELSEIF(CMAKE_COMPILER_IS_GNUCXX)
        SET(FBX_LIBNAME "fbxsdk-2014.1")
    ELSE()
        SET(FBX_LIBNAME "fbxsdk-2014.1")
    ENDIF()

    SET(FBX_LIBNAME_DEBUG ${FBX_LIBNAME}d)

    SET( FBX_SEARCH_PATHS
        $ENV{FBX_DIR}
        "$ENV{ProgramW6432}/Autodesk/FBX/FBX SDK/2014.1"
        "$ENV{PROGRAMFILES}/Autodesk/FBX/FBX SDK/2014.1"
        "/Applications/Autodesk/FBX/FBX SDK/2014.1"
        /Applications/Autodesk/FBXSDK20141
    )

    # search for headers & debug/release libraries
    FIND_PATH(FBX_INCLUDE_DIR "fbxsdk.h"
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES "include")
    FIND_LIBRARY( FBX_LIBRARY ${FBX_LIBNAME}
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES "lib/${FBX_LIBDIR}")

    FIND_LIBRARY( FBX_LIBRARY_DEBUG ${FBX_LIBNAME_DEBUG}
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES "lib/${FBX_LIBDIR}")
    IF(FBX_LIBRARY AND FBX_LIBRARY_DEBUG AND FBX_INCLUDE_DIR)
        SET(FBX_FOUND "YES")
    ELSE()
        SET(FBX_FOUND "NO")
    ENDIF()

ENDIF()

IF(NOT FBX_FOUND)
#try to use 2013.3 version
    IF(APPLE)
        SET(FBX_LIBNAME "fbxsdk-2013.3-static")
    ELSEIF(CMAKE_COMPILER_IS_GNUCXX)
        SET(FBX_LIBNAME "fbxsdk-2013.3-static")
    ELSE()
        SET(FBX_LIBNAME "fbxsdk-2013.3-md")
    ENDIF()

    SET(FBX_LIBNAME_DEBUG ${FBX_LIBNAME}d)

    SET( FBX_SEARCH_PATHS
        $ENV{FBX_DIR}
        "$ENV{ProgramW6432}/Autodesk/FBX/FBX SDK/2013.3"
        "$ENV{PROGRAMFILES}/Autodesk/FBX/FBX SDK/2013.3"
        "/Applications/Autodesk/FBX/FBX SDK/2013.3"
        /Applications/Autodesk/FBXSDK20133
    )

    # search for headers & debug/release libraries
    FIND_PATH(FBX_INCLUDE_DIR "fbxsdk.h"
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES "include")
    FIND_LIBRARY( FBX_LIBRARY ${FBX_LIBNAME}
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES "lib/${FBX_LIBDIR}")

    FIND_LIBRARY( FBX_LIBRARY_DEBUG ${FBX_LIBNAME_DEBUG}
        PATHS ${FBX_SEARCH_PATHS}
        PATH_SUFFIXES "lib/${FBX_LIBDIR}")
    IF(FBX_LIBRARY AND FBX_LIBRARY_DEBUG AND FBX_INCLUDE_DIR)
        SET(FBX_FOUND "YES")
    ELSE()
		MESSAGE("FBX_FOUND:NO FBX_LIBRARY=${FBX_LIBRARY} FBX_LIBRARY_DEBUG=${FBX_LIBRARY_DEBUG} FBX_INCLUDE_DIR=${FBX_INCLUDE_DIR}")
        SET(FBX_FOUND "NO")
    ENDIF()

ENDIF()
