find_path(FBX_INCLUDE_DIR NAMES fbxsdk.h PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include" NO_DEFAULT_PATH)
find_library(FBX_LIBRARY_RELEASE NAMES libfbxsdk-md PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" NO_DEFAULT_PATH)
find_library(FBX_LIBRARY_DEBUG   NAMES libfbxsdk-md PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib" NO_DEFAULT_PATH)
include(SelectLibraryConfigurations)
select_library_configurations(FBX)
set(FBX_LIBRARY "${FBX_LIBRARY}" CACHE STRING "")
unset(FBX_LIBRARY)
unset(FBX_FOUND)
if(NOT TARGET FBX::FBX)
    add_library(FBX::FBX UNKNOWN IMPORTED)
    set_target_properties(FBX::FBX PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${FBX_INCLUDE_DIR}"
        IMPORTED_CONFIGURATIONS RELEASE
        IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
        IMPORTED_LOCATION_RELEASE "${FBX_LIBRARY_RELEASE}"
    )
    if(FBX_LIBRARY_DEBUG)
        set_property(TARGET FBX::FBX APPEND PROPERTY
            IMPORTED_CONFIGURATIONS DEBUG)
        set_target_properties(FBX::FBX PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
            IMPORTED_LOCATION_DEBUG "${FBX_LIBRARY_DEBUG}")
    endif()
endif()
_find_package(${ARGS})
