set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
if(${PORT} MATCHES "openexr|imath|nvtt|jasper|freeglut|getopt|getopt_win32|dirent|gperf|freexl|szip|geos|nlohmann_json|netcfd_c|qhull|lerc|json_c|libpq|netcdf_c|uriparser")
	set(VCPKG_LIBRARY_LINKAGE static)
else()
	set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()